Implementa fromString e corregge alcuni bug
OpencontentCoop/ocevents pull request #25
Opened 2020-01-16 00:53 UTC by lrealdi

Verifica il popolamento se il campo è obbligatorio
Corregge la visualizzazione di edit da backend
Corregge alcuni bug di visualizzazione
Forza DTEND a rrule.js
Imposta l'identazione del codice php a 4 spazi

2020-01-16 00:55 UTC, lrealdi commented
@coppo guardala con https://github.blog/2018-05-01-ignore-white-space-in-code-review/

2020-01-18 10:50 UTC, lrealdi commented
ping @coppo

2020-01-18 11:05 UTC, coppo requested changes
Per il momento questo, sto scaricando per testare...oppure posso vederla da qualche parte?

2020-01-18 11:05 UTC, coppo commented on datatypes/ocevent/oceventtype.php
Perchè esportare anche le ricorrenze? non basta il pattern?

2020-01-18 11:05 UTC, coppo commented on datatypes/ocevent/oceventtype.php
> +    }
Anche qui se non sbaglio l'input prevede le ricorrenze ma poi le ricalcoli del pattern....

2020-01-18 11:12 UTC, lrealdi commented on classes/ocrecurrencehelper.php
> +                    throw new Exception("Invalid end date", 100);
100 cosi lo riconosco in chiamata e posso agire di conseguenza
vedi https://github.com/OpencontentCoop/ocevents/blob/feature_and_fix/design/standard/javascript/jquery.ocevent.js#L151

2020-01-18 11:13 UTC, lrealdi commented on datatypes/ocevent/oceventtype.php
Esporto gli eventi, non le ricorrenze, se sono diversi dalle ricorrenze

2020-01-18 11:14 UTC, lrealdi commented on datatypes/ocevent/oceventtype.php
> +    }
L'input è pattern|eventi
recurrence_pattern#start_timestamp-end__timestamp|start_timestamp-end__timestamp|...
se non hai eccezioni è sufficiente il pattern

2020-01-18 11:22 UTC, lrealdi commented
Qui la vedi in bs4
http://openagenda.openpa-dev.opencontent.it/

2020-01-18 11:35 UTC, coppo approved these changes

2020-01-18 11:36 UTC, coppo commented
Se riesci a metter "every" con la prima lettera in maiuscolo per il resto mi sembra tutto ok

2020-01-18 15:04 UTC, merged